version: '3'
services:
  overseerr:
    container_name: overseerr_dev
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 5055:5055
    volumes:
      - /home/freebox/overseerr/config:/config
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
